### PR TITLE
plugin functions/char: add char_length()

### PR DESCRIPTION
**Pull request by naoa**
I want to filter with charctor length as following.

```
select Users --filter 'char_length(name) == 2' --output_columns 'name' --command_version 2
```

### CODE REVIEW

**Comment by kou** [comment]
Thanks for your pull request.
How about `string_length()` instead of `char_length()`. Because `char_length()` should return length of ONE character.

**Comment by naoa** [comment]
I agree with your thought.

I'll change to ``string~`` from ``char~`` later.

**Comment by cosmo0920** [comment]
Nit: I think that if we use `string_length()` instead of `char_length()`, we should use `string~` name in file name and its test cases name.

**Comment by naoa** [comment]
I've renamed.
Also I've fixed CMakeLists.txt
Then I've squashed these commits.

**Comment by cosmo0920** [comment]
:+1:

**Comment by kou** [comment]
Thanks!

**Pull request merged**
