### PR TITLE
test: add no hit dynamic columns with output_columns without error

### PR DESCRIPTION
**Pull request by kenhys**
This test case checks whether output_columns with empty records of
dynamic columns (highlighted_content) in filtered stage doesn't cause
an error.

### CODE REVIEW

**Comment by kou** [comment]
It's better that we remove all records by `query` not `min` because `filtered` stage is executed after `query`.

**Comment by kenhys** [comment]
I think that  execution order is: min -> query -> filtered. so it is good enough by `min`. Is `query` better in this case because it reduces scope of processing pipeline?

**Comment by kou** [comment]
No records by `min` and no records by `query` use the different execution pass in implementation.

**Comment by kenhys** [comment]
I've fixed to use `--query 'content:@slow'` in this case.

**Comment by kou** [comment]
Merged.

**Pull request merged**
