### PR TITLE
packages source: fix new version addition to redirect list

### PR DESCRIPTION
**Pull request by komainu8**
For example, this script output .htaccess as below when we release PGroonga 3.0.3.

```
edirect /source/pgroonga/pgroonga-3.0.1.tar.gz https://github.com/pgroonga/pgroonga/releases/download/3.0.1/pgroonga-3.0.1.tar.gz
Redirect /source/pgroonga/pgroonga-3.0.1.tar.gz.asc https://github.com/pgroonga/pgroonga/releases/download/3.0.1/pgroonga-3.0.1.tar.gz.asc
Redirect /source/pgroonga/pgroonga-3.0.1.zip https://github.com/pgroonga/pgroonga/releases/download/3.0.1/pgroonga-3.0.1.zip 
Redirect /source/pgroonga/pgroonga-3.0.1.zip.asc https://github.com/pgroonga/pgroonga/releases/download/3.0.1/pgroonga-3.0.1.zip.asc
Redirect /source/pgroonga/pgroonga-3.0.2.tar.gz https://github.com/pgroonga/pgroonga/releases/download/3.0.2/pgroonga-3.0.2.tar.gz
Redirect /source/pgroonga/pgroonga-3.0.2.tar.gz.asc https://github.com/pgroonga/pgroonga/releases/download/3.0.2/pgroonga-3.0.2.tar.gz.asc
Redirect /source/pgroonga/pgroonga-3.0.2.zip https://github.com/pgroonga/pgroonga/releases/download/3.0.2/pgroonga-3.0.2.zip 
Redirect /source/pgroonga/pgroonga-3.0.2.zip.asc https://github.com/pgroonga/pgroonga/releases/download/3.0.2/pgroonga-3.0.2.zip.asc
Redirect /source/pgroonga/pgroonga-3.0.3.tar.gz https://github.com/pgroonga/pgroonga/releases/download/3.0.3/pgroonga-3.0.3.tar.gz
Redirect /source/pgroonga/pgroonga-3.0.3.tar.gz.asc https://github.com/pgroonga/pgroonga/releases/download/3.0.3/pgroonga-3.0.3.tar.gz.asc
Redirect /source/pgroonga/pgroonga-latest.tar.gz https://github.com/pgroonga/pgroonga/releases/download/3.0.3/pgroonga-3.0.3.tar.gz
Redirect /source/pgroonga/pgroonga-latest.tar.gz.asc https://github.com/pgroonga/pgroonga/releases/download/3.0.3/pgroonga-3.0.3.tar.gz.asc
Redirect /source/pgroonga/pgroonga-3.0.3.zip https://github.com/pgroonga/pgroonga/releases/download/3.0.3/pgroonga-3.0.3.zip 
Redirect /source/pgroonga/pgroonga-3.0.3.zip.asc https://github.com/pgroonga/pgroonga/releases/download/3.0.3/pgroonga-3.0.3.zip.asc
Redirect /source/pgroonga/pgroonga-latest.zip https://github.com/pgroonga/pgroonga/releases/download/3.0.3/pgroonga-3.0.3.zip 
Redirect /source/pgroonga/pgroonga-latest.zip.asc https://github.com/pgroonga/pgroonga/releases/download/3.0.3/pgroonga-3.0.3.zip.asc
```

### CODE REVIEW

**Comment by kou** [comment]
Hmm... It's too overkill...

I think that the following changes are enough:

```diff
diff --git a/packages/packages-groonga-org-package-task.rb b/packages/packages-groonga-org-package-task.rb
index fbe0cdfe7..50b364b4c 100644
--- a/packages/packages-groonga-org-package-task.rb
+++ b/packages/packages-groonga-org-package-task.rb
@@ -263,7 +263,6 @@ class PackagesGroongaOrgPackageTask < PackageTask
         "#{repository_rsync_base_path}/#{target_namespace}/#{@package}/"
       sh("rsync",
          "-av",
-         "--dry-run",
          "--include=.htaccess",
          "--exclude=*",
          rsync_dir,
@@ -285,7 +284,7 @@ class PackagesGroongaOrgPackageTask < PackageTask
       end
       File.open(htaccess_path, "w") do |htaccess|
         htaccess_content.each_line do |line|
-          htaccess.puts(line) unless line.include?("-latest-")
+          htaccess.puts(line) unless line.include?("-latest")
         end
         __send__("#{target_namespace}_targets").each do |target|
           redirect_url = built_package_url(target_namespace, target)
```

**Comment by komainu8** [comment]
Oh...

Your modification output ".htaccess" as below.

```
Redirect /source/pgroonga/pgroonga-3.0.3.tar.gz https://github.com/pgroonga/pgroonga/releases/download/3.0.3/pgroonga-3.0.3.tar.gz
Redirect /source/pgroonga/pgroonga-3.0.3.tar.gz.asc https://github.com/pgroonga/pgroonga/releases/download/3.0.3/pgroonga-3.0.3.tar.gz.asc
Redirect /source/pgroonga/pgroonga-latest.tar.gz https://github.com/pgroonga/pgroonga/releases/download/3.0.3/pgroonga-3.0.3.tar.gz
Redirect /source/pgroonga/pgroonga-latest.tar.gz.asc https://github.com/pgroonga/pgroonga/releases/download/3.0.3/pgroonga-3.0.3.tar.gz.asc
Redirect /source/pgroonga/pgroonga-3.0.3.zip https://github.com/pgroonga/pgroonga/releases/download/3.0.3/pgroonga-3.0.3.zip
Redirect /source/pgroonga/pgroonga-3.0.3.zip.asc https://github.com/pgroonga/pgroonga/releases/download/3.0.3/pgroonga-3.0.3.zip.asc
Redirect /source/pgroonga/pgroonga-latest.zip https://github.com/pgroonga/pgroonga/releases/download/3.0.3/pgroonga-3.0.3.zip
Redirect /source/pgroonga/pgroonga-latest.zip.asc https://github.com/pgroonga/pgroonga/releases/download/3.0.3/pgroonga-3.0.3.zip.asc
```

I think that redirect target is only a source of 3.0.3 in the above definition.
Should we redirect sources of 3.0.2, 3.0.1, and 3.0.0?

May be, I still don't understand this problem yet...

**Comment by askdkc** [comment]
> Should we redirect sources of 3.0.2, 3.0.1, and 3.0.0?

Outside script like Homebrew is dependent on these links so we should keep all these versions links.

**Comment by komainu8** [comment]
I confirm it as below.

```
export GROONGA_REPOSITORY=/path/to/groonga
cd packages
rake source:prepare
less source/repositories/source/pgroonga/.htaccess
```

I don't execute `rake source:download`...

**Comment by komainu8** [comment]
I confirm result of the following command.

```
(cd packages && GROONGA_REPOSITORY=/path/to/groonga rake source:download source:prepare && cat source/repositories/source/pgroonga/.htaccess)
```

"Redirect" definitions of a new version were added in existing "Redirect" definitions and rewrited latest version as below.

Definitions of 3.0.0, `tar.gz` of 3.0.1, `zip` of 3.0.2 don't define.
However, we can download these sources. Because these are already uploaded as `zip` and `tar.gz`.

```
Redirect /source/pgroonga/pgroonga-3.0.1.zip https://github.com/pgroonga/pgroonga/releases/download/3.0.1/pgroonga-3.0.1.zip
Redirect /source/pgroonga/pgroonga-3.0.1.zip.asc https://github.com/pgroonga/pgroonga/releases/download/3.0.1/pgroonga-3.0.1.zip.asc
Redirect /source/pgroonga/pgroonga-3.0.2.tar.gz https://github.com/pgroonga/pgroonga/releases/download/3.0.2/pgroonga-3.0.2.tar.gz
Redirect /source/pgroonga/pgroonga-3.0.2.tar.gz.asc https://github.com/pgroonga/pgroonga/releases/download/3.0.2/pgroonga-3.0.2.tar.gz.asc
Redirect /source/pgroonga/pgroonga-3.0.3.tar.gz https://github.com/pgroonga/pgroonga/releases/download/3.0.3/pgroonga-3.0.3.tar.gz
Redirect /source/pgroonga/pgroonga-3.0.3.tar.gz.asc https://github.com/pgroonga/pgroonga/releases/download/3.0.3/pgroonga-3.0.3.tar.gz.asc
Redirect /source/pgroonga/pgroonga-latest.tar.gz https://github.com/pgroonga/pgroonga/releases/download/3.0.3/pgroonga-3.0.3.tar.gz
Redirect /source/pgroonga/pgroonga-latest.tar.gz.asc https://github.com/pgroonga/pgroonga/releases/download/3.0.3/pgroonga-3.0.3.tar.gz.asc
Redirect /source/pgroonga/pgroonga-3.0.3.zip https://github.com/pgroonga/pgroonga/releases/download/3.0.3/pgroonga-3.0.3.zip
Redirect /source/pgroonga/pgroonga-3.0.3.zip.asc https://github.com/pgroonga/pgroonga/releases/download/3.0.3/pgroonga-3.0.3.zip.asc
Redirect /source/pgroonga/pgroonga-latest.zip https://github.com/pgroonga/pgroonga/releases/download/3.0.3/pgroonga-3.0.3.zip
Redirect /source/pgroonga/pgroonga-latest.zip.asc https://github.com/pgroonga/pgroonga/releases/download/3.0.3/pgroonga-3.0.3.zip.asc
```

I'll fix my modification in according to https://github.com/groonga/groonga/pull/1563#issuecomment-1552224197.

**Comment by kou** [comment]
They are problem of the existing `.htaccess`.
I've fixed it manually.

**Comment by komainu8** [comment]
Thanks!
I've apply your suggestion.

**Pull request merged**
