### PR TITLE
test: add tests for groonga-synonym-generate

### PR DESCRIPTION
**Pull request by kou**

### CODE REVIEW

**Comment by kou** [comment]
Cc: @HashidaTKS

**Comment by HashidaTKS** [comment]
The added tests seem to be failing, is that okey?
Sorry, I haven't investigated the reason yet.

**Comment by kou** [comment]
Good catch!
They are failed because groonga-httpd (nginx) rejects the large `load`. I changed `grntest` to increase the acceptable max body size.

**Review by HashidaTKS — APPROVED** [review]

**Comment by HashidaTKS** [comment]
Thanks for your explanation!

**Pull request merged**
