### PR TITLE
Added dockerfile

### PR DESCRIPTION
**Pull request by genki**
Added Dockerfile based on alpine linux image.

### CODE REVIEW

**Comment by kou** [comment]
Thanks.

How about creating a new repository for Docker as "groonga/docker" like mroonga/docker? If it's reasonable, I'll create a repository.

**Comment by genki** [comment]
@kou it's nice. Could you create it?

**Comment by kou** [comment]
Sure. I've created https://github.com/groonga/docker . You can have admin permission. Please commit the Dockerfile directly!

**Comment by genki** [comment]
@kou thanks!

**Comment by kou** [comment]
If you have an account on https://hub.docker.com/ , please tell me. I'll add you to "groonga" organization: https://hub.docker.com/u/groonga/

**Comment by genki** [comment]
@kou my account is [takiuchi](https://hub.docker.com/u/takiuchi/)

**Comment by kou** [comment]
Thanks. I've added you.
Now you can also use https://hub.docker.com/r/groonga/groonga/ .

**Comment by genki** [comment]
@kou  This repository seems normal repo. The automated build needs to have been setup by special way in the menu "Create Automated Build".

**Comment by kou** [comment]
Sorry. Could you try to recreate the repository? You have admin permission in the organization. If you can recreate the repository, we can confirm that you have right permission.

**Comment by genki** [comment]
okey, I will do it :)

**Comment by kou** [comment]
Thanks!

**Pull request closed without merging**
