### PR TITLE
test: add columns[NAME].flags test case without cache

### PR DESCRIPTION
**Pull request by kenhys**
When the value of --columns[NAME].flags parameter is changed, Groonga
returns result without using cache.

### CODE REVIEW

**Comment by kenhys** [comment]
WIP because there is no different between output of VECTOR_COLUMN and VECTOR_COLUMN|WITH_WEIGHT.

**Comment by kou** [comment]
How about adding any elements?

**Comment by kenhys** [comment]
It means that `.value 'vector_new(1, 2, 3)'` ? I've tried it but no difference.

**Comment by kou** [comment]
Ah. You need to use reference type or `ShortText` type for outputting weight vector. Or you can implement weight vector output for `uvector` in `grn_output_uvector()` at `output.c.

**Comment by kenhys** [comment]
I've updated the test case which uses `ShortText`.

**Comment by kou** [comment]
Merged.
Supporting outputting non reference column weight vector should be issued.

**Comment by kenhys** [comment]
I've created issue as #669

**Comment by kou** [comment]
Good!

**Comment by kenhys** [comment]
I've also created found issue as #670

**Pull request merged**
