### PR TITLE
docs: Add unify_latin_alphabet_with option to NormalizerNFKC150

### PR DESCRIPTION
**Pull request by abetomo**
To improve maintainability, we have plans to change the structure of the documentation.
That plan will consolidate the options into one page.
So I have only added it to NormalizerNFKC150 in this commit.

### CODE REVIEW

**Review by otegami — APPROVED** [review]
LGTM 👍🏾 (Thank you so much!)

**Comment by kou** [comment]
Could you run `ninja doc_update_files`?

**Comment by abetomo** [comment]
> Could you run `ninja doc_update_files`?

I ran `ninja doc_update_examples` and added the auto-generated `doc/source/example/reference/normalizers/normalizer-nfkc150-unify-latin-alphabet-with.log`.

**Comment by kou** [comment]
Is it `doc_update_examples` not `..._files`?

**Comment by abetomo** [comment]
Yes, to be exact I ran the following.

```
cmake -B ./groonga.build.doc -S . --preset=doc
cmake --build ./groonga.build.doc/
ninja doc_update_examples -C ./groonga.build.doc/
```

**Comment by kou** [comment]
We need to run `doc_update_files` when we add/remove any files.

**Comment by abetomo** [comment]
Oh, I see.
You were referring to a different task.

**Pull request merged**
