### PR TITLE
test: add no hit dynamic columns with drilldowns[LABEL].filter without error

### PR DESCRIPTION
**Pull request by kenhys**
This test case checks whether drilldowns[LABEL].filter with empty
records of dynamic columns (price_with_tax) in initial stage doesn't
cause an error.

### CODE REVIEW

**Comment by kou** [comment]
Ah, we should refer a column created by `drilldowns[LABEL].columns[NAME].stage initial` in `drilldowns[LABEL].filter`.

**Comment by kenhys** [comment]
Thanks.
I'll fix it.

**Comment by kenhys** [comment]
I've just fixed test case.

**Comment by kou** [comment]
There is a needless commit: https://github.com/groonga/groonga/pull/673/commits/2ada77138fb9dfc731e4bb3a3165992c70021fa5

**Comment by kenhys** [comment]
Just removed https://github.com/groonga/groonga/pull/673/commits/2ada77138fb9dfc731e4bb3a3165992c70021fa5 .

**Comment by kou** [comment]
Merged.

**Pull request merged**
