### PR TITLE
Fixed issue#43, Make enums UPPER_CASE

### PR DESCRIPTION
**Pull request by furandon-pig**
The enum value name to upper case(Issue #43).
Confirmed following thing.
* Success to compile in fixed code.
  * Use following configure option.
```
$ ./configure \
        --prefix=/tmp/groonga   \
        --with-pic              \
        --disable-benchmark     \
        --disable-glibtest      \
        --disable-document      \
        --disable-groonga-httpd \
        --disable-zeromq        \
        --without-libevent      \
        --enable-debug          \
        --enable-mruby=no
```
* Pass the test of "make check" and "run-test.sh".

### CODE REVIEW

**Comment by myokoym** [comment]
Thanks for the patch!

> Pass the test of "make check" and "run-test.sh".

Could you tell us all run commands and results without omission?
"run-test.sh" is located in two places in the repository:

```
% find . -name run-test.sh
./test/unit/run-test.sh
./test/command/run-test.sh
```

**Comment by kou** [comment]
Please do not it by one commit and one pull request. It's difficult to find a problem by this change.
Please process one enum by one pull request.

**Comment by furandon-pig** [comment]
> Could you tell us all run commands and results without omission?
> "run-test.sh" is located in two places in the repository:

I used groonga/test/unit/run-test.sh and attached result of groonga/test/unit/run-test.sh
```
Finished in 0.000116 seconds (total: 0.000000 seconds)

0 test(s), 0 assertion(s), 0 failure(s), 0 error(s), 0 pending(s), 0 omission(s), 0 notification(s)
0% passed
```
However, I seem like no execute test case(sorry, my careless oversight).
I don't know reason of why no execute test. Then I create new issue and wait advise.

**Comment by myokoym** [comment]
> I used groonga/test/unit/run-test.sh and attached result of groonga/test/unit/run-test.sh

Sorry, could you show **all** results of the command?

**Comment by furandon-pig** [comment]
> Please do not it by one commit and one pull request. It's difficult to find a problem by this change.
> Please process one enum by one pull request.

Sorry, I resend pull request each modified.
But I have a problem of execute test script. Deal with this problem.

**Comment by furandon-pig** [comment]
> Sorry, could you show all results of the command?

I attached all result. Nothing output other then summary of test result.
```
$ ./run-test.sh


Finished in 0.001547 seconds (total: 0.000000 seconds)

0 test(s), 0 assertion(s), 0 failure(s), 0 error(s), 0 pending(s), 0 omission(s), 0 notification(s)
0% passed
```

**Comment by kou** [comment]
Close because there is no progress in a few months.

**Pull request closed without merging**
