### PR TITLE
test: add columns[NAME].window.sort_keys test case without cache

### PR DESCRIPTION
**Pull request by kenhys**

### CODE REVIEW

**Comment by kou** [comment]
`UInt32` type `comment` column is a bit strange... I thought that `comment` column is`ShortText` type but I was wrong.

**Comment by kenhys** [comment]
I've fixed test case to use `logical_select`.

**Comment by kenhys** [comment]
There is one concern about test result. It seems that the value of `window_sum(price)` is calculated each `Logs_XXX`.

**Comment by kou** [comment]
Merged.

> There is one concern about test result. It seems that the value of `window_sum(price)` is calculated each `Logs_XXX`.

It should be documented as a limitation or implemented.

**Pull request merged**
