### PR TITLE
ci: increase timeout for HTTP chunked test

### PR DESCRIPTION
**Pull request by HashidaTKS**
HTTP chunked test is slower than others. We should improve performance for HTTP chunked
but we increase timeout for now.

### CODE REVIEW

**Comment by kou** [comment]
Do we need more timeout not only for chunked case?

**Comment by HashidaTKS** [comment]
Honestly, I don't decide whether we need `timeout` option for all `http` cases.
Recently, only the chunked case seems to time out but I guess it may occur in other `http` cases.
Does the chunked case do something special to occur timeout?

**Comment by kou** [comment]
> Does the chunked case do something special to occur timeout?

We need to comparing slower case deeply to identify it but the chunked case is slower than others obviously:

https://github.com/groonga/groonga/runs/5110173990?check_suite_focus=true

* `Test: stdio`: 7m10s
* `Test: HTTP: load: Apache Arrow`: 7m5s
* `Test: HTTP: command: POST`: 7m2s
* `Test: HTTP: command: chunked`: 8m13s
* `Test: HTTP: groonga-httpd`: 6m52s
* `Test: HTTP: reference count`: 7m49s

We may should improve performance of the chunked case as the real fix.

**Comment by HashidaTKS** [comment]
I see, I have removed the `timeout` option from not chunked cases.

**Pull request merged**
