### PR TITLE
test: add no hit dynamic columns with match_columns without error

### PR DESCRIPTION
**Pull request by kenhys**
This test case checks whether match_columns with empty records of
dynamic columns (price_with_tax) in initial stage doesn't cause an
error.

### CODE REVIEW

**Comment by kou** [comment]
`match_columns` isn't used when `query` isn't specified.

**Comment by kou** [comment]
Normally, `UInt32` value isn't used as `match_columns`. So test data isn't suitable.

**Comment by kenhys** [comment]
I've fixed test case with feedback.

**Comment by kou** [comment]
Merged!

**Pull request merged**
