### PR TITLE
expr adjust: fix invalid weight with multiple adjusts

### PR DESCRIPTION
**Pull request by komainu8**
GitHub: fix GH-1548

The weight value that a user specify is pushed in stack.
This value pop in `PARSE()`.
Currently, If we specify multiple weights in search query, Groonga pop the latest weight immediately after Groonga it push in stack.

Therefore, the latest weight doesn't apply result.
As a result, the previous weight is multiple applied.

In this modification, multiple weight are applied correctly by pushing weight in stack after Groonga execute `PARSE()`.

### CODE REVIEW

**Comment by kou** [comment]
Hmm...
We should pop in `.lemon` because nest information should be processed by Lemon.

It seems that we just need the following change:

```diff
diff --git a/lib/expr.c b/lib/expr.c
index 29fa00cea..cd7a13e70 100644
--- a/lib/expr.c
+++ b/lib/expr.c
@@ -4431,8 +4434,8 @@ parse_query_accept_adjust(grn_ctx *ctx,
                           float weight)
 {
   if (!(q->flags & GRN_EXPR_QUERY_NO_SYNTAX_ERROR)) {
-    parse_query_push_weight(ctx, q, weight);
     PARSE(token);
+    parse_query_push_weight(ctx, q, weight);
     return;
   }
```

**Comment by komainu8** [comment]
@kou Thank you for your comments.
I've fixed it and I added tests for this modification.

**Comment by kou** [comment]
Could you add why/when this problem is happen and how to fix this problem to the pull request description?

**Comment by komainu8** [comment]
I added he pull request description.

**Pull request merged**
